### ISSUE TITLE
Verification Error On Resnet18

### ISSUE THREAD

**Issue by TomHeaven** [xxradon/PytorchToCaffe#4]
This project helps a lot. However, I found a problem converting resnet18.

During the transformation, I got a warning message:
```
WARNING: the output shape miss match at max_pool1: input torch.Size([1, 64, 112, 112]) output---Pytorch:torch.Size([1, 64, 56, 56])---Caffe:torch.Size([1, 64, 57, 57])
This is caused by the different implementation that ceil mode in caffe and the floor mode in pytorch.
You can add the clip layer in caffe prototxt manually if shape mismatch error is caused in caffe. 
```
And the above warning leads to an error in verification:
```
F1225 20:18:19.848548 2458284928 net.cpp:757] Cannot copy param 0 weights from layer 'fc1'; shape mismatch.  Source param shape is 1000 512 (512000); target param shape is 1000 2048 (2048000). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
```

I need to manually design a crop layer to correct the size match, but I do not know how to do it. Caffe's crop layer requires two input layers.

There is a useless crop layer below:

```
layer {
  name: "max_pool1"
  type: "Pooling"
  bottom: "relu_blob1"
  top: "max_pool_blob1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 1
  }
}

layer {
  name: "crop_layer"
  type: "Crop"
  bottom: "max_pool_blob1"
  bottom: "max_pool_blob1"
  top: "cropped_blob1"
  crop_param {
    axis: 2
    offset: 0
    offset: 0
  }
}

layer {
  name: "conv2"
  type: "Convolution"
  bottom: "cropped_blob1"
  top: "conv_blob2"
  convolution_param {
    num_output: 64
    bias_term: false
    pad: 1
    kernel_size: 3
    stride: 1
    weight_filler {
      type: "xavier"
    }
    dilation: 1
  }
}
```

Any help is appreciated!

**Comment by xxradon** [comment]
@TomHeaven Actually,I had tested on my compter,resnet18 and 50 is all  ok.And then I will test it later.

**Comment by xiaxiaofu** [comment]
> This project helps a lot. However, I found a problem converting resnet18.
> 
> During the transformation, I got a warning message:
> 
> ```
> WARNING: the output shape miss match at max_pool1: input torch.Size([1, 64, 112, 112]) output---Pytorch:torch.Size([1, 64, 56, 56])---Caffe:torch.Size([1, 64, 57, 57])
> This is caused by the different implementation that ceil mode in caffe and the floor mode in pytorch.
> You can add the clip layer in caffe prototxt manually if shape mismatch error is caused in caffe. 
> ```
> And the above warning leads to an error in verification:
> 
> ```
> F1225 20:18:19.848548 2458284928 net.cpp:757] Cannot copy param 0 weights from layer 'fc1'; shape mismatch.  Source param shape is 1000 512 (512000); target param shape is 1000 2048 (2048000). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
> *** Check failure stack trace: ***
> ```
> I need to manually design a crop layer to correct the size match, but I do not know how to do it. Caffe's crop layer requires two input layers.
> 
> There is a useless crop layer below:
> 
> ```
> layer {
>   name: "max_pool1"
>   type: "Pooling"
>   bottom: "relu_blob1"
>   top: "max_pool_blob1"
>   pooling_param {
>     pool: MAX
>     kernel_size: 3
>     stride: 2
>     pad: 1
>   }
> }
> 
> layer {
>   name: "crop_layer"
>   type: "Crop"
>   bottom: "max_pool_blob1"
>   bottom: "max_pool_blob1"
>   top: "cropped_blob1"
>   crop_param {
>     axis: 2
>     offset: 0
>     offset: 0
>   }
> }
> 
> layer {
>   name: "conv2"
>   type: "Convolution"
>   bottom: "cropped_blob1"
>   top: "conv_blob2"
>   convolution_param {
>     num_output: 64
>     bias_term: false
>     pad: 1
>     kernel_size: 3
>     stride: 1
>     weight_filler {
>       type: "xavier"
>     }
>     dilation: 1
>   }
> }
> ```
> Any help is appreciated!

Input size should [1, 3, 222, 222] not  [1, 3, 224, 224]

**Comment by TomHeaven** [comment]
@xiaxiaofu Thanks! The caffe model runs smoothly after manually updating the head of `resnet18.prototxt` as
```
name: "resnet18"
input: "blob1"
input_dim: 1
input_dim: 3
input_dim: 222
input_dim: 222
```
That's the trick! Maybe the trick should be added to README. Anyway, I'm closing the issue.
