### ISSUE TITLE
无法转换 Avgpool2d

### ISSUE THREAD

**Issue by kyleleey** [xxradon/PytorchToCaffe#46]
不论在网络结构中使用mean还是avgpool2d函数，转换后都会转为caffe中的'Reduction'层，但我后期的部署中不支持这种层。不过PytorchToCaffe的源码中好像有转为caffe中poo层的代码，请问我应该如何在pytorch中应用avgpool功能？我的pytorch版本是1.2.0

**Comment by xxradon** [comment]
now master branch supoort avgpool2d

**Comment by kyleleey** [comment]
I see, thank you for that
