### ISSUE TITLE
模型转换之后精度相差较大

### ISSUE THREAD

**Issue by LilySys** [xxradon/PytorchToCaffe#47]
您好，利用您的工具，进行pytorch转caffe以及验证之后，一切显示正常，但是我在caffe之下大量测试模型的时候，caffe模型的map相较于pytorch模型的map低了10个点，本人的模型为resnet-50。我也试着从多方面查找问题，但还是没有头绪，希望您能给些建议，谢谢！

**Comment by xxradon** [comment]
可以使用我提供的verfy_deploy.py去对比pytorch和caffe每一层的输出。然后一般输出上的差异来源比较明显的是BN层引起的。

**Comment by LilySys** [comment]
我按照您说的方式，每一层进行对比，确实时BN层的差异夹大，请问是什么原因造成的，有没有办法可以解决？

**Comment by LilySys** [comment]
我按照您说的方式，每一层进行对比，确实发现是BN层的差异较大，请问是什么原因造成的，有没有办法可以解决？

**Comment by LilySys** [comment]
我按照您说的方式，每一层进行对比，确实发现是BN层的差异较大，误差达到2个数量级，请问是什么原因造成的，有没有办法可以解决？

**Comment by LilySys** [comment]
您好，或者说可以从哪些地方入手排查问题

**Comment by xxradon** [comment]
主要是BN层的默认参数，你仔细比对一下。

**Comment by LilySys** [comment]
是指caffe的还是pytorch的？

**Comment by LilySys** [comment]
以我浅薄的认识，我觉得caffe测试时用不到默认参数，除了eps，其余参数都是训练时使用，而pytorch测试除了用eps、track_running_stats也用不到其它默认参数了呀，其余的也是训练时使用。

**Comment by xxradon** [comment]
是的。主要就是这个eps的差异引起误差，当然你需要验证一下你到底使用的是哪个版本的caffe，intel 的caffe BN是单独一层，官方版的是bn+scale。
