### ISSUE TITLE
支持object detection model的转换吗？

### ISSUE THREAD

**Issue by 1976277169** [xxradon/PytorchToCaffe#6]
ssd的pytorch模型转caffe模型，请问支持吗？

**Comment by xxradon** [comment]
caffe ssd的模型需要支持permute op，由于本人没有这个需求，所以目前本工程还没有实现，你可以参考https://github.com/xxradon/PytorchToCaffe/blob/master/pytorch_to_caffe.py 其他op实现，然后自行添加。

**Comment by 1976277169** [comment]
好滴，谢谢~
