### ISSUE TITLE
Could I convert pytorch bilinear interpolate layer to caffe ?  And how should I do that?

### ISSUE THREAD

**Issue by nieyan** [xxradon/PytorchToCaffe#70]
https://github.com/xxradon/PytorchToCaffe/blob/da9e22c4d614f29d040dd2218b37e1a954bb0ee5/pytorch_to_caffe.py#L405

**Comment by 18022443868** [comment]
How did you solve the problem?

**Comment by immarioo** [comment]
hi, How did you solve the problem?
