### ISSUE TITLE
adaptiveavgpool

### ISSUE THREAD

**Issue by riskeverything** [xxradon/PytorchToCaffe#95]
I see the code,it seems support the adaptiveavgpool,but,when I use it,like:
Self.avgpool =  nn.AdaptiveAvgPool2d(1)
Y=self.avgpool(x).view(b,c)

It doesn’t work.and the error is type error None has type Nonetype,but expected one of bytes,Unicode

My env is pytorch 1.2,python 3.6

Can you give some suggestion,how can I fix it?

**Comment by accountcwd** [comment]
hi , @riskeverything 
i meet the same problem. Have you solved it?
If you had solved it could you share your solution？
Thanks！
